import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "@/components/blocks/Navbar"
import Footer from "@/components/blocks/Footer";
import BackgroundVideo from "./fundo/page";
import { CarrinhoProvider } from "@/context/CarrinhoContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RUBOTZ tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="PT-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossOrigin="anonymous"></script>
            
        <BackgroundVideo/>
        <Navbar />

        <CarrinhoProvider>{children}</CarrinhoProvider>
        <Footer />
        
      </body>
    </html>
  );
}
